<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-NLM9CQ8" failures="1" tests="2" name="Test Scenarios" time="15.932" errors="0" timestamp="2024-06-01T09:40:17 IST">
  <testcase classname="com.test.Swag.testcases.scenario_001" name="startpageAndlogin1" time="6.998"/>
  <testcase classname="com.test.Swag.testcases.scenario_001" name="startpageAndlogin2" time="2.357">
    <failure type="java.lang.AssertionError" message="expected [Epic sadface: Sorry, this user has been locked out] but found [Epic sadface: Sorry, this user has been locked out.]">
      <![CDATA[java.lang.AssertionError: expected [Epic sadface: Sorry, this user has been locked out] but found [Epic sadface: Sorry, this user has been locked out.]
at com.test.Swag.testcases.scenario_001.startpageAndlogin2(scenario_001.java:100)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- startpageAndlogin2 -->
</testsuite> <!-- Test Scenarios -->
